version: '3.8'

services:
  telejob:
    build: .
    container_name: telejob
    volumes:
      - ./migrations:/root/migrations
    env_file:
      - .env.${ENV:-prod}
    environment:
      TD_API_ID: ${TELEGRAM_API_ID}
      TD_API_HASH: ${TELEGRAM_API_HASH}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
    networks:
      - telejob-net

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: telejob
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - telejob-net

volumes:
  db-data:

networks:
  telejob-net:
    driver: bridge
